{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "40cffe48-5eed-480f-a279-60bf3546bb55",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting streamlit\n",
      "  Downloading streamlit-1.42.2-py2.py3-none-any.whl.metadata (8.9 kB)\n",
      "Collecting opencv-python\n",
      "  Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl.metadata (20 kB)\n",
      "Requirement already satisfied: tensorflow in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (2.18.0)\n",
      "Requirement already satisfied: pillow in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (11.1.0)\n",
      "Collecting altair<6,>=4.0 (from streamlit)\n",
      "  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting blinker<2,>=1.0.0 (from streamlit)\n",
      "  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)\n",
      "Collecting cachetools<6,>=4.0 (from streamlit)\n",
      "  Using cached cachetools-5.5.2-py3-none-any.whl.metadata (5.4 kB)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (8.1.8)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (1.26.4)\n",
      "Requirement already satisfied: packaging<25,>=20 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (24.2)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (2.2.3)\n",
      "Requirement already satisfied: protobuf<6,>=3.20 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (4.25.6)\n",
      "Collecting pyarrow>=7.0 (from streamlit)\n",
      "  Downloading pyarrow-19.0.1-cp311-cp311-win_amd64.whl.metadata (3.4 kB)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (2.32.3)\n",
      "Requirement already satisfied: rich<14,>=10.14.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (13.9.4)\n",
      "Collecting tenacity<10,>=8.1.0 (from streamlit)\n",
      "  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting toml<2,>=0.10.1 (from streamlit)\n",
      "  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from streamlit) (4.12.2)\n",
      "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
      "  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)\n",
      "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
      "  Downloading GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
      "Collecting tornado<7,>=6.0.3 (from streamlit)\n",
      "  Using cached tornado-6.4.2-cp38-abi3-win_amd64.whl.metadata (2.6 kB)\n",
      "Requirement already satisfied: tensorflow-intel==2.18.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow) (2.18.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.1.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=24.3.25 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (25.2.10)\n",
      "Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.6.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.2.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (18.1.1)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.4.0)\n",
      "Requirement already satisfied: setuptools in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (75.8.0)\n",
      "Requirement already satisfied: six>=1.12.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.17.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.5.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.17.2)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (1.70.0)\n",
      "Requirement already satisfied: tensorboard<2.19,>=2.18 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (2.18.0)\n",
      "Requirement already satisfied: keras>=3.5.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.8.0)\n",
      "Requirement already satisfied: h5py>=3.11.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (3.13.0)\n",
      "Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.4.1)\n",
      "Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorflow-intel==2.18.0->tensorflow) (0.31.0)\n",
      "Collecting jinja2 (from altair<6,>=4.0->streamlit)\n",
      "  Downloading jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)\n",
      "Collecting jsonschema>=3.0 (from altair<6,>=4.0->streamlit)\n",
      "  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)\n",
      "Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)\n",
      "  Downloading narwhals-1.28.0-py3-none-any.whl.metadata (10 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.1)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from requests<3,>=2.27->streamlit) (3.4.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from requests<3,>=2.27->streamlit) (2025.1.31)\n",
      "Requirement already satisfied: markdown-it-py>=2.2.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)\n",
      "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from rich<14,>=10.14.0->streamlit) (2.19.1)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.18.0->tensorflow) (0.45.1)\n",
      "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from jinja2->altair<6,>=4.0->streamlit) (3.0.2)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.1.0)\n",
      "Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Downloading referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)\n",
      "Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Downloading rpds_py-0.23.1-cp311-cp311-win_amd64.whl.metadata (4.2 kB)\n",
      "Requirement already satisfied: namex in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.0.8)\n",
      "Requirement already satisfied: optree in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.14.0)\n",
      "Requirement already satisfied: mdurl~=0.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)\n",
      "Requirement already satisfied: markdown>=2.6.8 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.7)\n",
      "Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (0.7.2)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in c:\\users\\kalik\\appdata\\roaming\\python\\python311\\site-packages (from tensorboard<2.19,>=2.18->tensorflow-intel==2.18.0->tensorflow) (3.1.3)\n",
      "Downloading streamlit-1.42.2-py2.py3-none-any.whl (9.6 MB)\n",
      "   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--\n",
      "   ------------- -------------------------- 3.1/9.6 MB 31.0 MB/s eta 0:00:01\n",
      "   ------------------- -------------------- 4.7/9.6 MB 11.0 MB/s eta 0:00:01\n",
      "   ----------------------- ---------------- 5.5/9.6 MB 9.6 MB/s eta 0:00:01\n",
      "   ------------------------- -------------- 6.0/9.6 MB 7.1 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 6.6/9.6 MB 6.3 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 7.9/9.6 MB 6.2 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 9.2/9.6 MB 6.2 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 9.6/9.6 MB 5.7 MB/s eta 0:00:00\n",
      "Using cached opencv_python-4.11.0.86-cp37-abi3-win_amd64.whl (39.5 MB)\n",
      "Downloading altair-5.5.0-py3-none-any.whl (731 kB)\n",
      "   ---------------------------------------- 0.0/731.2 kB ? eta -:--:--\n",
      "   ---------------------------------------- 731.2/731.2 kB 5.0 MB/s eta 0:00:00\n",
      "Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)\n",
      "Using cached cachetools-5.5.2-py3-none-any.whl (10 kB)\n",
      "Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)\n",
      "Downloading pyarrow-19.0.1-cp311-cp311-win_amd64.whl (25.3 MB)\n",
      "   ---------------------------------------- 0.0/25.3 MB ? eta -:--:--\n",
      "   -- ------------------------------------- 1.8/25.3 MB 8.4 MB/s eta 0:00:03\n",
      "   ----- ---------------------------------- 3.4/25.3 MB 8.4 MB/s eta 0:00:03\n",
      "   ------- -------------------------------- 4.7/25.3 MB 7.3 MB/s eta 0:00:03\n",
      "   -------- ------------------------------- 5.2/25.3 MB 7.2 MB/s eta 0:00:03\n",
      "   --------- ------------------------------ 6.3/25.3 MB 6.0 MB/s eta 0:00:04\n",
      "   ------------ --------------------------- 7.6/25.3 MB 6.0 MB/s eta 0:00:03\n",
      "   -------------- ------------------------- 8.9/25.3 MB 6.0 MB/s eta 0:00:03\n",
      "   --------------- ------------------------ 10.0/25.3 MB 6.0 MB/s eta 0:00:03\n",
      "   ---------------- ----------------------- 10.5/25.3 MB 5.7 MB/s eta 0:00:03\n",
      "   ----------------- ---------------------- 11.0/25.3 MB 5.3 MB/s eta 0:00:03\n",
      "   ------------------- -------------------- 12.1/25.3 MB 5.2 MB/s eta 0:00:03\n",
      "   --------------------- ------------------ 13.4/25.3 MB 5.2 MB/s eta 0:00:03\n",
      "   ----------------------- ---------------- 14.9/25.3 MB 5.5 MB/s eta 0:00:02\n",
      "   ------------------------- -------------- 16.3/25.3 MB 5.5 MB/s eta 0:00:02\n",
      "   -------------------------- ------------- 16.8/25.3 MB 5.3 MB/s eta 0:00:02\n",
      "   --------------------------- ------------ 17.6/25.3 MB 5.2 MB/s eta 0:00:02\n",
      "   ----------------------------- ---------- 18.9/25.3 MB 5.3 MB/s eta 0:00:02\n",
      "   ------------------------------- -------- 19.9/25.3 MB 5.3 MB/s eta 0:00:02\n",
      "   ---------------------------------- ----- 21.5/25.3 MB 5.4 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 22.3/25.3 MB 5.3 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 22.5/25.3 MB 5.2 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 23.6/25.3 MB 5.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 24.4/25.3 MB 5.0 MB/s eta 0:00:01\n",
      "   ---------------------------------------  25.2/25.3 MB 5.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 25.3/25.3 MB 5.0 MB/s eta 0:00:00\n",
      "Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
      "   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--\n",
      "   --------- ------------------------------ 1.6/6.9 MB 9.3 MB/s eta 0:00:01\n",
      "   ---------------- ----------------------- 2.9/6.9 MB 7.0 MB/s eta 0:00:01\n",
      "   ------------------------ --------------- 4.2/6.9 MB 6.6 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 5.0/6.9 MB 6.0 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 6.0/6.9 MB 5.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  6.8/6.9 MB 5.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.9/6.9 MB 5.2 MB/s eta 0:00:00\n",
      "Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)\n",
      "Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Using cached tornado-6.4.2-cp38-abi3-win_amd64.whl (438 kB)\n",
      "Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)\n",
      "Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "Downloading jinja2-3.1.5-py3-none-any.whl (134 kB)\n",
      "Downloading jsonschema-4.23.0-py3-none-any.whl (88 kB)\n",
      "Downloading narwhals-1.28.0-py3-none-any.whl (308 kB)\n",
      "Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)\n",
      "Downloading referencing-0.36.2-py3-none-any.whl (26 kB)\n",
      "Downloading rpds_py-0.23.1-cp311-cp311-win_amd64.whl (232 kB)\n",
      "Downloading smmap-5.0.2-py3-none-any.whl (24 kB)\n",
      "Installing collected packages: watchdog, tornado, toml, tenacity, smmap, rpds-py, pyarrow, opencv-python, narwhals, jinja2, cachetools, blinker, referencing, pydeck, gitdb, jsonschema-specifications, gitpython, jsonschema, altair, streamlit\n",
      "Successfully installed altair-5.5.0 blinker-1.9.0 cachetools-5.5.2 gitdb-4.0.12 gitpython-3.1.44 jinja2-3.1.5 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 narwhals-1.28.0 opencv-python-4.11.0.86 pyarrow-19.0.1 pydeck-0.9.1 referencing-0.36.2 rpds-py-0.23.1 smmap-5.0.2 streamlit-1.42.2 tenacity-9.0.0 toml-0.10.2 tornado-6.4.2 watchdog-6.0.0\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit opencv-python tensorflow pillow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c211f8ec-5ed9-42f9-9617-97659833b8e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Streamlit app file created as 'signloom_app.py'\n"
     ]
    }
   ],
   "source": [
    "code = \"\"\"\n",
    "import streamlit as st\n",
    "import tensorflow as tf\n",
    "import numpy as np\n",
    "import cv2\n",
    "import json\n",
    "\n",
    "# Load the trained model\n",
    "model = tf.keras.models.load_model('sign_language_model_transfer.keras')\n",
    "\n",
    "# Load class labels\n",
    "with open('class_labels.json', 'r') as f:\n",
    "    class_indices = json.load(f)\n",
    "class_labels = {v: k for k, v in class_indices.items()}\n",
    "\n",
    "# Preprocess the image for prediction\n",
    "def preprocess_frame(frame):\n",
    "    img = cv2.resize(frame, (128, 128))\n",
    "    img = img / 255.0\n",
    "    return np.expand_dims(img, axis=0)\n",
    "\n",
    "# Streamlit UI\n",
    "st.title(\"📸 SignLoom - Real-Time Sign Language Recognition\")\n",
    "st.write(\"Show a sign in front of your webcam and see the prediction!\")\n",
    "\n",
    "# Start Webcam\n",
    "run = st.checkbox('Start Webcam')\n",
    "\n",
    "FRAME_WINDOW = st.image([])\n",
    "\n",
    "# Initialize webcam\n",
    "cap = None\n",
    "\n",
    "if run:\n",
    "    cap = cv2.VideoCapture(0)\n",
    "\n",
    "    while run:\n",
    "        ret, frame = cap.read()\n",
    "        if not ret:\n",
    "            st.error(\"Failed to access webcam.\")\n",
    "            break\n",
    "\n",
    "        # Flip for mirror view\n",
    "        frame = cv2.flip(frame, 1)\n",
    "\n",
    "        # Preprocess & Predict\n",
    "        img_array = preprocess_frame(frame)\n",
    "        prediction = model.predict(img_array)\n",
    "        predicted_class = np.argmax(prediction, axis=1)[0]\n",
    "        predicted_label = class_labels.get(predicted_class, \"Unknown\")\n",
    "\n",
    "        # Display Prediction on Frame\n",
    "        cv2.putText(frame, f'Sign: {predicted_label}', (10, 40),\n",
    "                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)\n",
    "\n",
    "        # Convert BGR to RGB for Streamlit\n",
    "        FRAME_WINDOW.image(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))\n",
    "\n",
    "    cap.release()\n",
    "else:\n",
    "    st.write(\"✅ Click 'Start Webcam' to begin.\")\n",
    "\"\"\"\n",
    "\n",
    "# Write the code to a .py file\n",
    "with open('SignLoom_app.py', 'w', encoding='utf-8') as f:\n",
    "    f.write(code)\n",
    "\n",
    "print(\"✅ Streamlit app file created as 'signloom_app.py'\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "a9ac9b5f-f9cc-4d61-b774-747ddcdf2216",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run signloom_app.py\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "c1c993e3-3352-4871-9055-2ca771387c8d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (hand_env)",
   "language": "python",
   "name": "hand_env"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
